%show_image.m
%function to visualize imported images
%
%(c) Johannes Picker
%=========================================================================%
% Version history
%13.04.2023     Johannes Picker     creation of file
%=========================================================================%
% Usage:
%   show_image(img, ui_runs, ui_kpis, ui_layerCount)
%Inputs:
%   img, ui_runs, ui_kpis, ui_layerCount
%Outputs:
%   gui window
%Globals:
%   none
%=========================================================================%
% Notes:

% prompt for layer, run...
% run button
% show image in plot

function show_image(img, ui_runs, ui_kpis, ui_layerCount)  
runs.Value = 1;
kpis.Value = 1;
layers.Value = 1;

fig = uifigure('Name','Show Images');
fig.Position(3:4) = [440 320];

ax = uiaxes('Parent',fig,...
    'Position',[10 10 300 300]);

cbx = uicheckbox(fig,...
    'Position',[320 220 100 20],...
    'Text','AutoUpdate?',...
    'Value', 0);

runs = uidropdown(fig,...
    'Position',[320 190 100 20],...
    'Items',ui_runs,...
    'ItemsData',1:length(ui_runs),...
    'Value',1, ...
    'ValueChangedFcn',@(runs,event) autoUpdate(...
               cbx,ax,img,runs.Value,kpis.Value,layers.Value));

kpis = uidropdown(fig,...
    'Position',[320 160 100 20],...
    'Items',ui_kpis,...
    'ItemsData',1:length(ui_kpis),...
    'Value',1, ...
    'ValueChangedFcn',@(kpis,event) autoUpdate(...
               cbx,ax,img,runs.Value,kpis.Value,layers.Value));

layers = uispinner(fig,'Limits', [1  ui_layerCount],...
    'Position',[320 130 100 20],...
    'LowerLimitInclusive','on',...
    'UpperLimitInclusive','on',...
    'Value', 1, ...
    'ValueChangedFcn',@(layers,event) autoUpdate(...
               cbx,ax,img,runs.Value,kpis.Value,layers.Value));

btn = uibutton(fig,'push',...
               'Text', 'Refresh',...
               'Position',[320 100 100 20],...
               'ButtonPushedFcn', @(btn,event) showImage(...
               ax,img,runs.Value,kpis.Value,layers.Value));

showImage(ax,img,runs.Value,kpis.Value,layers.Value)
end


% Create the function for the ButtonPushedFcn callback
function autoUpdate(cbx,ax,img,run,kpi,layer)
    if cbx.Value 
        imagesc(ax,img{run,kpi,layer})
    end
end

function showImage(ax,img,run,kpi,layer)
    imagesc(ax,img{run,kpi,layer})
end
